import type { ObjectKey } from "../../core/ids.ts";
import type { IdOf, Tag } from "../../core/tag.ts";
import type { FindObjectsOptions, ObjectQuery } from "../../query/types.ts";
import type { AuxStore } from "./aux-store.ts";
import type { AuxCodec, TagShape } from "./codec.ts";

/**
 * Pre-initialization interface for a storage adapter — the type accepted
 * by `setupTagikon`. After {@link StorageAdapterSetup.initialize} is called,
 * the adapter transitions to {@link StorageAdapter} and data operations
 * become available.
 *
 * Splitting the lifecycle across two interfaces lets the type system
 * prevent calling data operations before the adapter has been initialized.
 *
 * @example Implementing an adapter
 * ```ts
 * class MyAdapter<TTag extends Tag> implements StorageAdapterSetup<TTag> {
 *   initialize(tagShape: TagShape<TTag>): StorageAdapter<TTag> {
 *     // capture tagShape.id (IdProvider) and per-property codecs
 *     return this as unknown as StorageAdapter<TTag>;
 *   }
 *   // ...data operations
 * }
 * ```
 */
export interface StorageAdapterSetup<TTag extends Tag = Tag> {
	/**
	 * Initializes the adapter with the tag shape — both the ID provider
	 * (via `tagShape.id`) and per-property codecs for serialization.\
	 * Must be called exactly once before any data operation.
	 *
	 * @throws `StorageAdapterAlreadyInitializedError` if called more than once.
	 * @returns The initialized adapter ready for data operations.
	 */
	initialize(tagShape: TagShape<TTag>): StorageAdapter<TTag>;
}

/**
 * Persistence layer for tags, tag↔object relations, and per-extension
 * auxiliary stores. Returned by {@link StorageAdapterSetup.initialize};\
 * never instantiated directly.
 *
 * Concrete implementations should pass the `runStorageAdapterTests`
 * contract suite from `@tagikon/core/testing`.
 *
 * @typeParam TTag - The concrete tag type (`extends Tag`).
 */
export interface StorageAdapter<TTag extends Tag = Tag> {
	/**
	 * Persists a new tag. The ID is generated by the configured IdProvider
	 * inside the adapter.
	 *
	 * @throws {@link TagAlreadyExistsError} if the adapter enforces uniqueness
	 *   and `data` collides with an existing tag.
	 */
	createTag(data: Omit<TTag, "id">): Promise<TTag>;

	/** @returns The tag with `id`, or `null` if no such tag exists. */
	getTag(id: IdOf<TTag>): Promise<null | TTag>;

	/** @returns Every tag currently stored. Order is not guaranteed. */
	listTags(): Promise<TTag[]>;

	/**
	 * Patches a tag in place.
	 *
	 * @throws {@link TagNotFoundError} if no tag with `id` exists.
	 */
	updateTag(id: IdOf<TTag>, patch: Partial<Omit<TTag, "id">>): Promise<TTag>;

	/**
	 * Deletes a tag.
	 *
	 * @returns `true` if a tag was deleted, `false` if it did not exist
	 *   (no-op).
	 */
	deleteTag(id: IdOf<TTag>): Promise<boolean>;

	/**
	 * Attaches `tagId` to multiple objects. Idempotent — relations that
	 * already exist are left untouched.
	 *
	 * @throws {@link TagNotFoundError} if no tag with `tagId` exists.
	 */
	addRelations(tagId: IdOf<TTag>, objectKeys: readonly ObjectKey[]): Promise<void>;

	/**
	 * Removes the relation between `tagId` and each `objectKey`.\
	 * Missing relations are silently ignored.
	 */
	removeRelations(tagId: IdOf<TTag>, objectKeys: readonly ObjectKey[]): Promise<void>;

	/**
	 * @returns IDs of every tag attached to `objectKey`. Empty array if the
	 *   object has no tags (or does not exist — Tagikon has no concept of
	 *   an object outside of tag relations).
	 */
	listObjectTags(objectKey: ObjectKey): Promise<IdOf<TTag>[]>;

	/**
	 * @returns Object keys attached to `tagId`. Empty array if no objects
	 *   carry the tag, or if the tag does not exist.
	 */
	listTagObjects(tagId: IdOf<TTag>): Promise<ObjectKey[]>;

	/**
	 * Finds object keys matching `query`. Results are sorted lexicographically
	 * by the underlying string so that `limit`/`offset` pagination is
	 * deterministic.\
	 * Adapters that cannot compile the query natively should delegate to
	 * {@link evaluateObjectQueryInMemory} from `@tagikon/core`.
	 *
	 * @param options - `limit` caps result count; `offset` skips that many
	 *   results before returning. Both default to no-limit / no-skip.
	 */
	findObjects(query: ObjectQuery<IdOf<TTag>>, options?: FindObjectsOptions): Promise<ObjectKey[]>;

	/**
	 * Counts object keys matching `query`.\
	 * Adapters that cannot compile the query natively should delegate to
	 * {@link countObjectQueryInMemory} from `@tagikon/core`.
	 */
	countObjects(query: ObjectQuery<IdOf<TTag>>): Promise<number>;

	/**
	 * Returns the per-extension auxiliary store keyed by `extensionId`.\
	 * The same `extensionId` symbol must return the same {@link AuxStore}
	 * instance across calls. The runtime uses this to bind each extension's
	 * `ctx.aux`; this method itself must not be reachable from extensions.
	 *
	 * @param auxCodec - Optional codec for serializing/deserializing values.\
	 *   If omitted, the adapter falls back to its default (typically JSON
	 *   parsed via {@link safeJsonParse} for prototype-pollution safety).
	 */
	getAuxStore<TData = unknown>(
		extensionId: symbol,
		auxCodec?: AuxCodec<TData>,
	): AuxStore<IdOf<TTag>, TData>;
}
